const ACTION_TYPES = {
  //INCREMENT_COUNTER: 'INCREMENT_COUNTER',
  //DECREMENT_COUNTER: 'DECREMENT_COUNTER',

  INCREMENT_COUNTER: Symbol(),
  DECREMENT_COUNTER: Symbol(),

  GET_USERS_REQUEST: Symbol(),
  GET_USERS_SUCCESS: Symbol(),
  GET_USERS_ERROR: Symbol(),

  LOGIN_USER_REQUEST: Symbol(),
  LOGIN_USER_SUCCESS: Symbol(),
  LOGIN_USER_ERROR: Symbol(),

  GET_TASK_ACTION: Symbol(),

  GET_TASK_REQUEST: Symbol(),
  GET_TASK_SUCCESS: Symbol(),
  GET_TASK_ERROR: Symbol(),
};

export default ACTION_TYPES;
